channel_url: "https://www.youtube.com/@Gerakanwakafsumur/videos"
languages: ["id", "en"]
sleep_interval: 2
similarity_threshold: 0.75
use_stemming: false
exclude_series: true
output_file: "data/output/laporan_duplikat_konten.xlsx"
subtitle_dir: "data/subtitles"
audio_fallback: true
whisper_model: "small"
